### ISSUE TITLE
Specify a convention for pose matrices

### ISSUE THREAD

**Issue by FabienDanieau** [pollen-robotics/python-template#9]
Do we call pose matrices T_world_camera, or from_world_to_camera? etc

**Comment by FabienDanieau** [comment]
We had this discussion [here](https://discord.com/channels/519098054377340948/1044640931997044787/1062317115828346920)
Shall we use this [ref](https://gtsam.org/gtsam.org/2020/06/28/gtsam-conventions.html)? -> transform from frame a to b is noted *aTb*
or the one from modern robotics (ref needed) -> transform from frame a to b is noted *T_a_b*

More generally a reference document and some examples should be provided

**Comment by RemiFabre** [comment]
A proposal with some remarks.

## Meaning
I believe that aTb or T_a_b or a_T_b conventionally does not mean "transform from frame a to b", instead it means the opposite.
T_a_b == the frame b expressed in the frame a. So it's useful to transform points from frame b to frame a.
e.g let P_b_x be the point x expressed in frame b and P_a_x the point x expressed in frame a, then: 
P_a_x = T_a_b * P_b_x

## Conventions and scope
Any convention is fine by me, we used the Modern Robotics' convention in the Vision POC we can continue with it, but afaik they don't cover everything we need when coding. So here's a proposal.
I like the mnemotechnic trick of "frames of the same name are close", so I would prefix the frame of reference when naming a point.
T_a_c = T_a_b * T_b_c  --> Transform composition. The 2 "b" are close, we feel safe :)
P_a_x = T_a_b * P_b_x --> Application to a point. The 2 "b" are close, we feel safe :)

**Names should be 1 word long to avoid confusion**. Otherwise this is ambiguous: T_shoulder_camera_wrist, is it a transformation from the wrist to the shoulder_camera, or a transformation from the camera_wrist to the shoulder?

We could use capital letters for 3D and lower case letters for 2D:
- "3D homogeneous transformation matrix" --> A pose or transformation (letter T) is a 4x4 matrix with a 3x3 rotation matrix (letter R) + 3x1 column vector (for translation) + 1x4 column vector (for padding). Here a point is a 3D vector (letter P).
- "2D homogeneous transformation matrix" --> A pose or transformation (letter t) is a 3x3 matrix with a 2x2 rotation matrix (letter r) + 3x1 column vector (for translation)  + 1x3 row vector (for padding). Here a point is a 2D vector (letter p).

There are other cases but I wouldn't create a convention for them (like sometimes it's useful to pad the 3x3 rotation matrix into a 4x4 rotation matrix...).

**What matters is that someone reading your code doesn't struggle to understand it, so if you encounter a situation that's not covered by these conventions just add a clear comment explaining your stuff and be locally coherent with it**

## Code example
Using Python and numpy arrays.
if:
T_camera_object == The 4x4 pose of the object in the camera frame
T_torso_camera == The 4x4 pose of the camera in the torso frame
T_torso_object == The 4x4 pose of the object in the torso frame
then this code is correct:
`T_torso_object = T_torso_camera @ T_camera_object`

We can also define the rotation matrix of the transform:
`R_torso_object = T_torso_object[:3, :3]`

The 3D point object in the torso frame:
`P_torso_object = T_torso_object[:3, 3]`

Which is the same thing as the coordinates x, y and z of the object in the torso frame:
`x = T_torso_object[0][3]
 y = T_torso_object[1][3]
 z = T_torso_object[2][3]`

## References
This post uses Modern Robotics' conventions (which is coherent with my proposal)
https://www.mecharithm.com/homogenous-transformation-matrices-configurations-in-robotics/



Feel free to comment/change stuff

**Comment by apirrone** [comment]
I like the modern robotics convention because I am used to it :) 
Moreover I like the easiness to understand that `T_a_c = T_a_b @ T_b_c` just from reading the line.

Ok for naming points `P_a_b` and rotations `R_a_b`. Not sure if it is necessary but it should make some situations clearer.
